### ISSUE TITLE
should add exception handling code here

### ISSUE THREAD

**Issue by zer0ken** [Shtelo/MinicIV#1]
variable `member` can be `None` in the code below,

https://github.com/Shtelo/MinicIV/blob/62a1733485b7101acf52a0f84a296a1d496dee5b/cogs/extraessential_cog.py#L338

so you must handle the exception; AttributeError.

**Comment by junhg0211** [comment]
handled.
i recently noticed that there is an error with shtelian raspberry pi which member converter is not working on there, so our babel and attendance listing commands will not be working. if you know any of why, please let me know.
thanks.
